//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJob
    {
        public int JobId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> EmployerId { get; set; }
        public string SalaryRange { get; set; }
        public string JobType { get; set; }
        public string JobDetails { get; set; }
        public Nullable<bool> isFeaturedJob { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblEmployer tblEmployer { get; set; }
    }
}
