//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineRecruitment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobSeeker
    {
        public int JobSeekerId { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Skills { get; set; }
        public string JobType { get; set; }
        public string CurrentPosition { get; set; }
        public string HighestDegree { get; set; }
        public string ExpectedSalary { get; set; }
        public string Experience { get; set; }
        public string Resume { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
